---
ID: "71d49c21-a5d5-4fc4-8bb4-dfc0feb469b6"
Parent: "d5c5a83f-f26e-4492-97d3-8e73356a371b"
Template: "e35eaa2d-edea-431c-a9e6-488272b53782"
Path: /sitecore/client/Your Apps/UserAuditReport/UsersListing/PageSettings
DB: core
BranchID: "ef643281-0f7f-41f0-9af3-93e2da21a9a6"
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170304T120739Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
