---
ID: "37e3bc54-a0d7-4e87-b32e-029ff5ca3a2e"
Parent: "ab3d5fac-b175-42ef-9ba2-d01815d8ad3c"
Template: "ab3d5fac-b175-42ef-9ba2-d01815d8ad3c"
Path: /sitecore/client/Your Apps/UserAuditReport/UsersListing/Renderings/UserAuditList/UserAuditList Parameters/__Standard Values
DB: core
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170304T144730Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
